language: php
php:
  - 5.5
  - 5.4
  - hhvm
os:
  - linux
  - osx
install:
  - cd tests
  - if [ -n "$TRAVIS_TAG" ]; then composer require jerome-breton/casperjs-installer=$TRAVIS_TAG ; fi
  - rm -rf vendor composer.lock
  - composer install
script: vendor/bin/casperjs --version
